### ISSUE TITLE
License

### ISSUE THREAD

**Issue by heinrichreimer** [seansegal/tincisnotcatan#5]
Is your code licensed? I'm Heinrich from the Computer Science student's council in Halle, Germany.
We're trying to create a collection of online open source board and card games and we would be happy to include your great app!
So have you thought about licensing your code under any open source license?

**Comment by seansegal** [comment]
Just added an MIT license! Happy to hear you enjoy the app and would love to be part of your collection :)

**Comment by heinrichreimer** [comment]
Awesome! Thanks for the quick reply!
We're trying to host as much games as possible, because we need to switch to online events.
You can see a list of the currently working games here: https://games.fsr-matheinfo.de/
